controllers:
    resource: ../src/Controller/
    type: attribute

kernel:
  resource: ../src/Kernel.php
  type: annotation
  # type: lexik_jwt_authentication.handler.authentication_failure


api_login_check:
  path: /api/login_check
